### ISSUE TITLE
64 bits build problem

### ISSUE THREAD

**Issue by malickf** [e4lam/xlkit#1]
Hi, I have tried to build the example for a 64 bits plateform. I got the following (boost) compilation error : 
Erreur  C2065   'stdcall_cc' :  not declared .. xlkitExample   .... xlkit.hpp  296
Is this code only for 32 bits plateforms ? 

Thanks,

**Comment by e4lam** [comment]
It shouldn't, which boost version are you using?

-Edward

**Comment by e4lam** [comment]
Ah sorry, you may be right since I was compiling for 32-bit Excel on 64-bit Windows. Try removing instances of stdcall_cc from the code. I wouldn't expect boost to omit the symbol when compiling for 64-bit though since __stdcall is still allowed by Visual Studio (although ignored on 64-bit).

-Edward

**Comment by malickf** [comment]
Hi, thanks i'll try to remove it from the code and post the modified version
